root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -buildvcs=false -o ./bin/gantry ./cmd/gantry"
  bin = "./bin/gantry"
  args_bin = ["serve","--port", "8089", "--plugin-dir", "/var/home/michael/workspace/11-mcgantry/feature-test-external-plugin-system/plugins"]
  include_ext = ["go"]
  exclude_dir = ["bin", "data", "local", "tmp", "web", "vendor"]
  exclude_regex = ["_test\\.go$"]
  exclude_unchanged = true
  delay = 500
  stop_on_error = true
  kill_delay = "2s"
  send_interrupt = true

[log]
  time = true

[color]
  build = "yellow"
  runner = "green"
  watcher = "cyan"
  app = ""

[misc]
  clean_on_exit = true
